### ISSUE TITLE
anidex not working python 3.8

### ISSUE THREAD

**Issue by ngosang** [nindogo/qbtSearchScripts#10]
```
nova3]$ python3 nova2.py anidex all one
Connection error: Forbidden
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "nova2.py", line 136, in run_search
    engine.search(what, cat)
  File "/home/kizar/Downloads/qbit/data/qBittorrent/nova3/engines/anidex.py", line 96, in search
    total_results = re.findall(r'Showing[^f]+f(.+?)torrents', webpage)[0].strip().replace(',', '')
IndexError: list index out of range
"""
```

**Comment by LastExceed** [comment]
> Connection error: Forbidden

anidex added ddos protection
